---
# CORREGIDO: Nginx ahora se maneja via Docker Compose, no instalación nativa
# El objetivo es que Nginx esté en contenedor Docker según requerimientos del taller

- name: Configurar servidor Jenkins con Docker
  hosts: jenkins_servers
  become: true

  tasks:
    - name: Actualizar cache de paquetes
      apt:
        update_cache: yes

    - name: Instalar dependencias para Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Agregar la clave GPG oficial de Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Agregar el repositorio de Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    - name: Actualizar cache después de agregar repositorio
      apt:
        update_cache: yes

    - name: Instalar Docker
      apt:
        name: docker-ce
        state: present

    - name: Añadir usuario al grupo Docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Instalar Docker Compose
      shell: |
        curl -L "https://github.com/docker/compose/releases/download/2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    - name: Establecer vm.max_map_count para SonarQube
      sysctl:
        name: vm.max_map_count
        value: "262144"
        state: present
        reload: yes

    - name: Crear directorio para configuración
      file:
        path: /home/{{ ansible_user }}/docker-devops
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Copiar docker-compose.yml
      copy:
        src: docker-compose.yml
        dest: /home/{{ ansible_user }}/docker-devops/docker-compose.yml
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Copiar configuración nginx
      copy:
        src: nginx.conf
        dest: /home/{{ ansible_user }}/docker-devops/nginx.conf
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Iniciar servicios con docker-compose
      docker_compose:
        project_src: /home/{{ ansible_user }}/docker-devops
        state: present
      become_user: "{{ ansible_user }}"
      become_method: su

    - name: Esperar que Jenkins esté disponible
      uri:
        url: http://localhost:8080
        method: GET
      register: jenkins_response
      until: jenkins_response.status == 200
      retries: 30
      delay: 10
      become_user: "{{ ansible_user }}"